# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XTM
version:      0.36
version_from: lib/XTM/base.pm
installdirs:  site
requires:
    Data::Dumper:                  2.102
    File::Slurp:                   
    File::stat:                    0
    Getopt::Long:                  2.25
    IO::File:                      1.08
    IO::String:                    1.01
    LWP::Simple:                   1.35
    Parse::RecDescent:             1.8
    Pod::Usage:                    1.14
    Term::ReadLine:                0
    Test:                          1.15
    Test::More:                    0.4
    Text::Iconv:                   1.2
    URI:                           1.18
    URI::file:                     0
    XML::SAX::ParserFactory:       1.01
    XML::Twig:                     3.01
    XML::Writer:                   0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
